name: VERSATIL Framework Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write
  actions: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci

    - name: Build framework
      run: npm run build

    - name: Run full test suite
      run: npm run validate

    - name: Generate release notes
      run: |
        echo "🚀 VERSATIL SDLC Framework ${GITHUB_REF#refs/tags/}" > release-notes.md
        echo "" >> release-notes.md
        echo "## 🎯 What's New" >> release-notes.md
        echo "" >> release-notes.md
        git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> release-notes.md || echo "- Initial release of VERSATIL SDLC Framework" >> release-notes.md
        echo "" >> release-notes.md
        echo "## 📦 Installation" >> release-notes.md
        echo "" >> release-notes.md
        echo "\`\`\`bash" >> release-notes.md
        echo "npm install -g versatil-sdlc-framework@${GITHUB_REF#refs/tags/v}" >> release-notes.md
        echo "\`\`\`" >> release-notes.md
        echo "" >> release-notes.md
        echo "## 🚀 Quick Start" >> release-notes.md
        echo "" >> release-notes.md
        echo "\`\`\`bash" >> release-notes.md
        echo "versatil init    # Interactive setup wizard" >> release-notes.md
        echo "versatil health  # Check framework status" >> release-notes.md
        echo "versatil analyze # Get agent recommendations" >> release-notes.md
        echo "\`\`\`" >> release-notes.md
        echo "" >> release-notes.md
        echo "## 🔗 Resources" >> release-notes.md
        echo "" >> release-notes.md
        echo "- 📖 [Documentation](https://github.com/MiraclesGIT/versatil-sdlc-framework#readme)" >> release-notes.md
        echo "- 🤖 [BMAD Methodology Guide](https://github.com/MiraclesGIT/versatil-sdlc-framework/blob/main/CLAUDE.md)" >> release-notes.md
        echo "- 💬 [Community Discussions](https://github.com/MiraclesGIT/versatil-sdlc-framework/discussions)" >> release-notes.md
        echo "" >> release-notes.md
        echo "---" >> release-notes.md
        echo "" >> release-notes.md
        echo "🤖 Generated with VERSATIL SDLC Framework" >> release-notes.md

    - name: Create GitHub Release
      uses: gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        name: VERSATIL Framework ${{ github.ref_name }}
        body_path: release-notes.md
        draft: false
        prerelease: false

    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Update package version tracking
      run: |
        echo "✅ Released VERSATIL Framework ${{ github.ref_name }}"
        echo "📦 Published to NPM: https://www.npmjs.com/package/versatil-sdlc-framework"
        echo "🔗 GitHub Release: https://github.com/MiraclesGIT/versatil-sdlc-framework/releases/tag/${{ github.ref_name }}"